[package]
name = "bpftime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.5", features = ["derive"] }
dirs = "5.0.1"
exec = "0.3.1"
libbpf-rs = { version = "0.21.2" }

[build-dependencies]
bindgen = "0.68.1"
